sonata_user:
  security_acl: true
  manager_type: orm # can be orm or mongodb
  class:            # Entity Classes
    user:               App\Entity\User
    group:              App\Entity\Group
  admin:            # Admin Classes
    user:
      class:    Sonata\UserBundle\Admin\Model\UserAdmin
    group:
      class:    Sonata\UserBundle\Admin\Model\GroupAdmin

  #Mailer config
  mailer: fos_user.mailer.noop